### ISSUE TITLE
[PE-D][Tester A] Multiple Help Windows

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T10-4/tp#196]
Two help windows can be created at the same time. One from startup and another from the help button.

![Screenshot 2022-10-28 at 16.43.06.png](https://raw.githubusercontent.com/NicholasPatrick/ped/main/files/08928138-ea64-4e52-b088-2f577acac5be.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: NicholasPatrick/ped#1

**Comment by onepersonhere** [comment]
Will Fix
