### ISSUE TITLE
UG: Grammar Error in Details of each field

### ISSUE THREAD

**Issue by onepersonhere** [AY2223S1-CS2103T-T10-4/tp#288]
![image](https://user-images.githubusercontent.com/51043502/200150004-7f9b2842-090d-4056-b137-c958af62351e.png)

**Comment by onepersonhere** [comment]
![image](https://user-images.githubusercontent.com/51043502/200150059-6d3589a6-4110-43de-8d35-f95fb5fb95ad.png)

under managing your friends

**Comment by zbz-lvlv** [comment]
![image](https://user-images.githubusercontent.com/9377433/200150269-87bede8e-3187-4ea7-9def-42504d17c3bf.png)

Existing tags
