### ISSUE TITLE
DG: Grammar

### ISSUE THREAD

**Issue by onepersonhere** [AY2223S1-CS2103T-T10-4/tp#298]
![image](https://user-images.githubusercontent.com/51043502/200150601-8b472641-519f-4464-a048-f6a5b2886f1a.png)
prefers

**Comment by onepersonhere** [comment]
![image](https://user-images.githubusercontent.com/51043502/200150688-a976ba99-d002-4c0b-bdb0-15486d74f661.png)
is*

**Comment by zbz-lvlv** [comment]
![image](https://user-images.githubusercontent.com/9377433/200150884-d711dd6b-765a-4c40-b568-e0fc29cc2805.png)

that are available

**Comment by onepersonhere** [comment]
![image](https://user-images.githubusercontent.com/51043502/200150885-0ca679ae-e2a5-43f0-8b76-3faaf30c576c.png)
are*

**Comment by onepersonhere** [comment]
![image](https://user-images.githubusercontent.com/51043502/200151005-d676009a-f5df-4a9f-b258-84232a274ece.png)
are

**Comment by onepersonhere** [comment]
![image](https://user-images.githubusercontent.com/51043502/200151120-480b8956-5e62-4429-99c8-daa61b5cc9ae.png)
GameTypes

**Comment by onepersonhere** [comment]
![image](https://user-images.githubusercontent.com/51043502/200151128-7583e1d8-08fb-4360-b7f8-6d3d7d8e8ee4.png)
they are displayed

**Comment by onepersonhere** [comment]
![image](https://user-images.githubusercontent.com/51043502/200151823-267341a8-17d9-4af3-b073-803dcc3e6079.png)
given keywords & intervals

**Comment by onepersonhere** [comment]
![image](https://user-images.githubusercontent.com/51043502/200151948-fa443d8d-1006-41dc-bc38-21a68cf299ab.png)
As we encountered, the other one change to had

**Comment by onepersonhere** [comment]
![image](https://user-images.githubusercontent.com/51043502/200151967-679aba08-1e22-4ea2-90a2-a5203aacd669.png)

**Comment by onepersonhere** [comment]
![image](https://user-images.githubusercontent.com/51043502/200151977-c92e6636-ad51-4d88-80ae-327e5d21f381.png)

**Comment by shawnkai** [comment]
> ![image](https://user-images.githubusercontent.com/51043502/200151967-679aba08-1e22-4ea2-90a2-a5203aacd669.png)

changed this to thus instead
